### ISSUE TITLE
I tried to use it but it never work

### ISSUE THREAD

**Issue by Abdelzaher-web** [dword-design/nuxt-mail#100]
please make video about how to use it in nuxt by example pleas .

**Comment by dword-design** [comment]
@Abdelzaher-web Phew I think I won't manage to do this. It's some effort to make an instructional video :). What is your problem or your error message? Maybe we can figure it out and make it work and then I can add some instructions to the README.md.

**Comment by Abdelzaher-web** [comment]
I want to know how I get smtp host and what  should I write in username and pass? Because i tried sendgrid host and i wrote in username "apiKey" and my api key in pass but it work in nodemailer and not work in nuxt-mail

**Comment by Abdelzaher-web** [comment]
> @Abdelzaher-web Phew I think I won't manage to do this. It's some effort to make an instructional video :). What is your problem or your error message? Maybe we can figure it out and make it work and then I can add some instructions to the README.md.

I want to know how I get smtp host and what should I write in username and pass? Because i tried sendgrid host and i wrote in username "apiKey" and my api key in pass but it work in nodemailer and not work in nuxt-mail.

My error code 500

**Comment by dword-design** [comment]
@Abdelzaher-web Check the actual error of the 500 response like documented [here](https://github.com/dword-design/nuxt-mail#debugging-mail-errors) and put it here. Let's find out if it is an auth issue or something else.

**Comment by Abdelzaher-web** [comment]
> @Abdelzaher-web Check the actual error of the 500 response like documented [here](https://github.com/dword-design/nuxt-mail#debugging-mail-errors) and put it here. Let's find out if it is an auth issue or something else.

I cant find any thing about error 500 [here](https://github.com/dword-design/nuxt-mail#debugging-mail-errors) . Please explain to me

**Comment by dword-design** [comment]
@Abdelzaher-web It's under "Debugging mail errors". Do a text search in the browser 😅.

**Comment by Abdelzaher-web** [comment]
> @Abdelzaher-web It's under "Debugging mail errors". Do a text search in the browser 😅.

Do yo mean search in google about error 500 ?

**Comment by dword-design** [comment]
No ctrl+f on the page.

**Comment by Abdelzaher-web** [comment]
> No ctrl+f on the page.

ok i did what do you write in the page and found error message "self signed certificate in certificate chain" how can i solve it

**Comment by Abdelzaher-web** [comment]
> No ctrl+f on the page.

pleas help me

**Comment by dword-design** [comment]
Sounds like this is the same issue:
https://github.com/dword-design/nuxt-mail/issues/62

Closing this in favor of the linked one.
