### ISSUE TITLE
Nuxt mail not working in production

### ISSUE THREAD

**Issue by wash03** [dword-design/nuxt-mail#103]
Good afternoon.

How do I make nuxt-mail work correctly on my hosting?
Running locally my project sends emails normally, but when deploying to production, emails are not sent.

**Comment by dword-design** [comment]
Hey @wash03, did you have a look at [this](https://github.com/dword-design/nuxt-mail#note-about-production-use) section in the readme?

**Comment by wash03** [comment]
Sorry, I didn't look
