### ISSUE TITLE
Support for nuxt 3

### ISSUE THREAD

**Issue by vencho-mdp** [dword-design/nuxt-mail#108]

**Comment by GithubMitch** [comment]
I really need this working with Nuxt 3 , im using nuxt.config.ts.
So following your tutorial gives me the following error in nuxt.config.ts:
Type '{ message: { to: string; }; smtp: { host: string; port: number; }; }' is not assignable to type 'string'.

**Comment by vencho-mdp** [comment]
@GithubMitch Ttill they release it for Nuxt 3, you could make a route under `server/api` that uses nodemailer :)

**Comment by niklasfjeldberg** [comment]
@dword-design do you have any update on this?

**Comment by kissu** [comment]
Related SO question: https://stackoverflow.com/q/73962200/8816585

**Comment by dword-design** [comment]
Nuxt 3 support is there. I can't reproduce the Typescript issue though, let me know if there is still an issue.

**Comment by mubaidr** [comment]
> Nuxt 3 support is there. I can't reproduce the Typescript issue though, let me know if there is still an issue.

Awesome! In that case this module should be listed under modules section (nuxt 3 website)
