### ISSUE TITLE
Cannot assign to read only property 'exports' of object '#<Object>'

### ISSUE THREAD

**Issue by Redemption198** [dword-design/nuxt-mail#109]
After installing this module I get this error: `Cannot assign to read only property 'exports' of object '#<Object>'`

Which seems to be caused by:

>   function(module2, __webpack_exports__, __webpack_require__) {
    (function(module3) {
      __webpack_require__(0);
      Object.defineProperty(exports, "__esModule", {
        value: true
      });
      exports.default = void 0;
      var _default = (context, inject) => inject("mail", {
        send: async (config) => {
          try {
            await context.app.$axios.$post("/mail/send", config);
          } catch (error) {
            throw new Error(error.response.data);
          }
        }
      });
      exports.default = _default;
      module3.exports = exports.default; <--- ERROR
    }).call(this, __webpack_require__(62)(module2));

**Comment by dword-design** [comment]
@Redemption198 Where can this snippet be found?
