### ISSUE TITLE
You have to provide to/cc/bcc in all configs

### ISSUE THREAD

**Issue by franciscoGPS** [dword-design/nuxt-mail#119]
I'm having this error while running an app with nuxt-mail. Is this error known for someone?

Thanks in advance!

![image](https://user-images.githubusercontent.com/6760672/156908602-94081152-24b2-4f77-95a8-019e3e668c7e.png)

**Comment by dword-design** [comment]
I guess you have a message config without to or cc or bcc like the error states. Can you show me your nuxt-mail config?

**Comment by nezlicodes** [comment]
@dword-design, I'm having the same build error:

Here's my config, I tried adding cc and bcc fields but still getting the error.
Any hint on how to fix this ?
>   [
      "nuxt-mail",
      {
        message: {
          to: process.env.EMAIL_TO,
          cc: process.env.EMAIL_TO,
          bcc: process.env.EMAIL_TO,
        },
        smtp: {
          host: "smtp.gmail.com",
          port: 587,
          auth: {
            user: process.env.EMAIL_USER,
            pass: process.env.EMAIL_PASS,
          },
        },
      },
    ],

**Comment by nezlicodes** [comment]
@franciscoGPS @dword-design  fixed this by adding the correct variable values in my prod .env file.

**Comment by tim3ks** [comment]
> message: {
> to: process.env.EMAIL_TO,
> cc: process.env.EMAIL_TO,
> bcc: process.env.EMAIL_TO,
> },

how to pass from client side in nuxt 3 email 'to' ?

**Comment by Loosie94** [comment]
@dword-design 

Is this possible with a HTML form, keeping the original "to" e-mail address?
