### ISSUE TITLE
Installation from npm fails

### ISSUE THREAD

**Issue by vikputthiscodeongit** [dword-design/nuxt-mail#15]
> 42 error code ENOENT
> 43 error syscall spawn git
> 44 error path git
> 45 error errno -4058
> 46 error enoent Error while executing:
> 46 error enoent undefined ls-remote -h -t ssh://git@github.com/dword-design/endent.git
> 46 error enoent
> 46 error enoent
> 46 error enoent spawn git ENOENT
> 47 error enoent This is related to npm not being able to find a file.

Are the errors I get when doing `npm install`. Happens on both my laptop and my PC, both running node 14.16 on Windows. I already tried removing my package.json like suggested online, but to no avail. I think it may have something to do with the referred project's settings.

**Comment by dword-design** [comment]
Hey @vikputthiscodeongit, what exactly were your steps? Did you install the module into your project or did you clone this repo?

**Comment by vikputthiscodeongit** [comment]
I got the error when trying to install the module to my project by running `npm install nuxt-mail` from the command line.

However I must say I solved the problem, to which the solution turned out to be rather silly. The error message I posted was logged to the error log, but I hadn't actually realized what information the error message in the command line had given me: the git binary can't be found. I have GitHub installed on both machines, but not the separate git binary - only on my work machine. After installing it the module installation proceeded just fine. 

Something is different with this module's installation compared to others though, as I've never encountered this problem before in all the times I added a npm module to a project on either my PC or laptop.

**Comment by dword-design** [comment]
@vikputthiscodeongit Ah alright makes sense. The problem could have been that I'm using some forked projects as indirect dependencies, which are installed from GitHub. The error message you got about [endent](https://github.com/indentjs/endent) is related to that. Not sure how NPM installs these dependencies, maybe it uses the `git` binary behind the scenes.
