### ISSUE TITLE
Insecure?

### ISSUE THREAD

**Issue by mathe42** [dword-design/nuxt-mail#18]
When installed this allowes all users to send mails to anybody. This is not secure and can be abused for spam or mails that are send in your or your company names!

I can provide a full working example if needed.

**Comment by dword-design** [comment]
@mathe42 I think you're right. So we would have to remove the `to` field from the message config and inject it via the module config. This way it could only be sent to the configured email address. Did I miss something?

Thanks for investigating!

**Comment by dword-design** [comment]
@mathe42 If you have a working example, feel free to share it.

**Comment by mathe42** [comment]
Same for cc and bcc. Just overwrite them with values form nuxt config...

**Comment by dword-design** [comment]
Sounds good. I'd say this is a breaking change.

**Comment by dword-design** [comment]
@mathe42 I linked a PR. Any objections?

**Comment by mathe42** [comment]
Yes. see #21

**Comment by dword-design** [comment]
@mathe42 Jeez, I messed up the places here. Of course we have to fix the route. I did some small adjustments, but apart from that I'm fine with it. I also added the tests from my PR. What do you think?

**Comment by mathe42** [comment]
LGTM.

I didn't look at the tests - don't have the time for it. But rest looks good to me.

**Comment by dword-design** [comment]
@mathe42 Alright it's merged. Fyi: I renamed mail to message to match the naming of nodemailer. Thanks for contributing 🥳.
