### ISSUE TITLE
Custom "to" address

### ISSUE THREAD

**Issue by RiaColaco05** [dword-design/nuxt-mail#23]
Is there a way to pass the "to" email address while calling the  /mail/send API ?

Eg:
this.$axios.$post('/mail/send', {
  to: "test@gmail.com",
  from: 'John Doe',
  subject: 'Incredibles',
  text: 'This is an incredible test message',
})
This does not work. 
Or is there a way to create different apis with different "to" address?

**Comment by dword-design** [comment]
@mathe42 You are pretty busy I guess but I could need your opinion on this 😀. I think the module needs a secure way to provide multiple email configs.

**Comment by mathe42** [comment]
My idea:
Same nuxt config but:
```js
this.$axios.$post('/mail/send', { config: 1, from: 'John Doe', ... })
```

And if config is not set or out of range use config 0 as fallback.

And allow message to be a single object that allways get used.

(name for parmeter `config` is bad but I could thought of a better one...)

**Comment by dword-design** [comment]
@mathe42 Yeah that was exactly what I thought and I added my suggestion in my comment above. Would it be something like `typeIndex` then and it refers to the index in the array? A mapping object would be cleaner but breaking.

**Comment by dword-design** [comment]
@mathe42 Yeah that looks good for a first shot. Maybe the `config` name is not too bad after all, what do you think? It refers to the message config. I'm a bit unsure if we should call such properties like what they actually do (`configIndex`), or if we should keep it flexible (in case we want to provide some nicer mechanism like named configs).

**Comment by mathe42** [comment]
Not shure. Naming something is not something I'm good in.

**Comment by dword-design** [comment]
Ok, apart from the naming: This index mechanism is a quick way to make the multi-config thing possible. In the long run I guess something like this is more cleaner, what do you think?

```js
// nuxt.config.js
export default {
  modules: [
    ['nuxt-mail', {
      message: {
        a: { bcc: 'xyz@foo.de' },
        b: { to: 'a@foo.de', cc: 'b@foo.de' },
      },
    ],
  ],
}
```

```
this.$axios.$post('/mail/send', { type: 'a', from: 'John Doe', ... })
// Uses the first message record
```

It's more work for a single config though, so maybe the index thing is better than it looks at first sight 😄.

**Comment by dword-design** [comment]
@RiaColaco05 What do you think about it?

**Comment by dword-design** [comment]
@RiaColaco05 Not yet

**Comment by dword-design** [comment]
I think we can add a `name` property to the message configs and use this as a reference. Then `{ config: 'foo' }` refers to the config with name `foo`, `{ config: 1 }` refers to the config with index 1, and if it is not set, it takes the config object itself (or the one with name `default` maybe).

**Comment by RiaColaco05** [comment]
Seems great :), if there isn't a config with name `default` in the nuxt config js file, then we will need a fallback config, maybe keep the first one from the `message` as fallback?

**Comment by dword-design** [comment]
@RiaColaco05 @mathe42 Alright I have the PR adjusted, tested, and documented. Feel free to have a quick look. I could merge it then.

**Comment by dword-design** [comment]
Alright it's merged. gl hf 🥳
