### ISSUE TITLE
Static hosting and nuxt generate

### ISSUE THREAD

**Issue by liquidiert** [dword-design/nuxt-mail#3]
Hey @dword-design, have you ever tried nuxt generate and host it statically? Cause for me it's not working. I guess it is cause of the intermediary express server? But a wild guess here. Anyway could you take a look at it? :)

**Comment by dword-design** [comment]
Hey @liquidiert, that will probably be the problem. Since generated sites only run client-side, these sites would need to use a third party email service or an embedded contact form or something similar. I guess this module only works with a server.

**Comment by dword-design** [comment]
@liquidiert Closing this for now. Feel free to reopen it again.
