### ISSUE TITLE
var $mail and the route /mail/send doesn't exists

### ISSUE THREAD

**Issue by boodcode** [dword-design/nuxt-mail#4]
Hi
/mail/send route and var $mail doesn't exist after install and config in nuxt.config.js 

any ideas ??

**Comment by dword-design** [comment]
@boodcode Hey, sounds a bit like the module isn't activated (not correctly configured in nuxt.config.js)? Otherwise the easiest would be to share some repo so I can have a look.

**Comment by phillipmohr** [comment]
Same problem.

Within my nuxt.config.js
```
mail: {
    smtp: {
        host: "myserver.server.com",
        port: 465,
        secure: true,
        auth: {
            user: 'username', // generated ethereal user
            pass: 'userpass', // generated ethereal password
        },
    },
},
```
Within the ContactForm.vue

```
methods: {
    onSubmit() {
        this.$axios.$post('/mail/send', {
            from: this.name,
            subject: `Kontaktformular [${this.request}]`,
            text: this.message,
            to: 'info@myserver.de',
        })
    }
},
```

Am I missing something?

Thanks in advance!

**Comment by dword-design** [comment]
@phillipmohr Thanks for the hint! Do you have a public repository that reproduces it?
