### ISSUE TITLE
Remove $axios as a dependency

### ISSUE THREAD

**Issue by madebyfabian** [dword-design/nuxt-mail#66]
Hi there!

Really love the plugin, but one thing is very misleading. The docs say that you can send a message like this:
```javascript
// Inside a component
this.$mail.send({
  from: 'John Doe',
  subject: 'Incredible',
  text: 'This is an incredible test message',
})
```
but actually I can't, because I don't have the nuxt/axios module installed. Maybe simply change this
```javascript
inject('mail', {
    send: config => context.app.$axios.$post('/mail/send', config)
});
```
into window.fetch(...)?

Best,
Fabian

**Comment by dword-design** [comment]
Hey @madebyfabian, the docs say that `@nuxtjs/axios` needs to be installed. Does it work if you add it before `nuxt-mail`?
Apart from that, I'd like to get rid of `@nuxtjs/axios`, but not entirely sure if it can be replaced completely because it does some nice stuff under the hood like using the Nuxt configured server and port and allowing to set a `baseURL`. I'm pretty open here, maybe up for a PR?

**Comment by madebyfabian** [comment]
Thanks for your comment!
Sorry, I've totally overread that part of installing @nuxtjs/axios.
I think for ppl not using the @nuxtjs/axios plugin it would be better to not have to install it _only_ for this single use case. 
I will take a look into it and if I find a solution without @nuxtjs/axios, I'll create a PR :) I think for example we could check if @nuxtjs/axios is installed, if yes, use it, if not, get those configs from nuxt directly and pass it into a window.fetch.
Anyways, thanks again for making this :)

**Comment by dword-design** [comment]
@madebyfabian You're welcome :).

Regarding the fetch: Just note that sending also needs to work server side, not only client side.

**Comment by madebyfabian** [comment]
I've worked on an implementation on a fork, currently using fetch on client-side, which looks like this:
https://github.com/madebyfabian/nuxt-mail/blob/removing-nuxt-axios-as-dependency/src/plugin.js

I've tested it, and it perfectly works when no @nuxtjs/axios is installed. 

Will have a look if there is also a possibility to get it to work at server-side, without any dependencies. Do you might have some examples in which cases the $mail.send could be called on server-side?

**Comment by dword-design** [comment]
@madebyfabian Use case is pretty much the same as client side but you submit a form, which will post the current route and then you get the request parameters server-side (e.g. via `asyncData`). Then you send the email via `context.app.mail.send(...)`. Kinda the "traditional way" of sending a contact form like you would in PHP.

**Comment by madebyfabian** [comment]
Thanks for the example, I thought something very similar. So i managed to get it to work on client- and server-side. Actually, nuxt automatically uses node-fetch instead of window.fetch when you are using it on the server-side. But I got the following error:

<img width="771" alt="Bildschirmfoto 2021-07-06 um 22 47 05" src="https://user-images.githubusercontent.com/32813692/124664674-18fe6b00-deac-11eb-97d3-eedc4f3c3c52.png">

Which basically says that node-fetch can't fetch /mail/send, since It doesn't know on which hostname this endpoint is.
I fixed this, but with a little downside. See here:
https://github.com/madebyfabian/nuxt-mail/blob/removing-nuxt-axios-as-dependency/src/plugin.js#L19-L22

The downside is, that
- when you don't have @nuxtjs/axios installed
- and you call $mail.send on server-side, 

it will call the endpoint with unsafe http, even if you're currently on a https endpoint. But because it's an internal call that happens on the server itsself, I think it should be fine. What do you think? The problem is, that nuxt doesn't know the current url it's on. I am only able to get the current hostname from the http-headers in `context.req.headers`. And the hostname comes without information about if we're on https or http.

**Comment by dword-design** [comment]
@madebyfabian hmm I think I need to have a close look on this. But I'm pretty busy at the moment unfortunately.

**Comment by dword-design** [comment]
Note: Other possibility is to add `@nuxtjs/axios` implicitly. Closing https://github.com/dword-design/nuxt-mail/issues/28 in favor of this one.

**Comment by dword-design** [comment]
@madebyfabian I have an [open PR](https://github.com/dword-design/nuxt-mail/pull/112) that would solve the issue feel free to have a look!

**Comment by dword-design** [comment]
Closed since Nuxt 3 is on the go
